## Homework 2

### 1. Collaborative Filtering, Kernels, Linear Regression

In this question, we will use the alternating projections algorithm for low-rank matrix factorization, which aims to minimize

$$J(U, V) = \underbrace{\frac{1}{2}\sum _{(a,i) \in D} (Y_{ai} - [UV^ T]_{ai})^2}_{\text {Squared Error}} + \underbrace{\frac{\lambda }{2}\sum _{a=1}^ n \sum _{j=1}^ k U_{aj}^2 + \frac{\lambda }{2}\sum _{i=1}^ m \sum _{j=1}^ k V_{ij}^2}_{\text {Regularization}}.$$

-----

#### 1. (a)

In [11]:
import numpy as np

# Initialize U and V
U : np.ndarray = np.asarray([[6, 0, 3, 6]]).T
V : np.ndarray = np.asarray([[4, 2, 1]])

# Compute X (UV^T)
X = U * V

print("X(0)")
print(X)

X(0)
[[24 12  6]
 [ 0  0  0]
 [12  6  3]
 [24 12  6]]


#### 2. (b)

In [13]:
# Initial data
# (Nan values are unknowns)
Y : np.ndarray = np.array(
    [
        [     5, np.nan,      7],
        [np.nan,      2, np.nan],
        [     4, np.nan, np.nan],
        [np.nan,      3,      6]
    ]
)

# Known values (D)
D = np.where(~np.isnan(Y))

# Squared error (For known values)
squared_error = 0.5 * np.sum( (Y[D]- X[D])**2 )

# Regularization terms
lambd : int = 1
regularization = (lambd / 2) * ( np.sum(U**2) + np.sum(V**2) )

print("Squared Error: ", squared_error)
print("Regularization: ", regularization)

Squared Error:  255.5
Regularization:  51.0


#### 1. (c)

In [15]:
# | U1 | | 4  2  1 |
# | U2 |
# | U3 | 
# | U4 |

# | 4U1 2U1 U1 |
# | 4U2 2U2 U2 |
# | 4U3 2U3 U3 |
# | 4U4 2U4 U4 |

# dU1 = 0.5*(5-4U1)^2 + 0.5*(7-U1)^2 + 0.5*lambda*U1^2
#     = -4*(5-4U1) - (7-U1) + lambda*U1
#     = -20 + 16U1 - 7 + U1 + lambda*U1
#     = -27 + 17U1 + lambda*U1 = 0
U1 = 27 / (lambd + 17)

# dU2 = 0.5*(2-2U2)^2 + 0.5*lambda*U2^2
#     = -2*(2-2U2) + lambda*U2
#     = -4 + 4U2 + lambda*U2 = 0
U2 = 4 / (lambd + 4)

# dU3 = 0.5*(4-4U3)^2 + 0.5*lambda*U3^2
#     = -4*(4-4U3) + lambda*U3
#     = -16 + 16U3 + lambda*U3 = 0
U3 = 16 / (lambd + 16)

# dU4 = 0.5*(3-2U4)^2 + 0.5*(6-U4)^2 + 0.5*lambda*U4^2
#     = -2*(3-2U4) - (6-U4) + lambda*U4
#     = -6 + 4U4 - 6 + U4 + lambda*U4
#     = -12 + 5U4 + lambda*U4 = 0
U4 = 12 / (lambd + 5)

print("[", U1, U2, U3, U4, "]")

[ 1.5 0.8 0.9411764705882353 2.0 ]
